export const CURRENCIES: any = [
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Argentina",
        enName: "Argentina",
        alpha2Code: "AR",
        alpha3Code: "ARG",
        viCurrencyName: "Peso Argentina",
        iso4217code: "ARS",
        locate: "es_AR",
        id: 1
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Úc",
        enName: "Australia",
        alpha2Code: "AU",
        alpha3Code: "AUS",
        viCurrencyName: "Đô la Úc",
        iso4217code: "AUD",
        locate: "en_AU",
        id: 2
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Áo",
        enName: "Austria",
        alpha2Code: "AT",
        alpha3Code: "AUT",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "de_AT",
        id: 3
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Bỉ",
        enName: "Belgium",
        alpha2Code: "BE",
        alpha3Code: "BEL",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "nl_BE",
        id: 4
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Bolivia",
        enName: "Bolivia",
        alpha2Code: "BO",
        alpha3Code: "BOL",
        viCurrencyName: "Boliviano Bolivia",
        iso4217code: "BOB",
        locate: "es_BO",
        id: 5
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Brasil",
        enName: "Brazil",
        alpha2Code: "BR",
        alpha3Code: "BRA",
        viCurrencyName: "Real Brasil",
        iso4217code: "BRL",
        locate: "pt_BR",
        id: 6
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Brunei",
        enName: "Brunei",
        alpha2Code: "BN",
        alpha3Code: "BRN",
        viCurrencyName: "Đô la Brunei",
        iso4217code: "BND",
        locate: "ms_BN",
        id: 7
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Canada",
        enName: "Canada",
        alpha2Code: "CA",
        alpha3Code: "CAN",
        viCurrencyName: "Đô la Canada",
        iso4217code: "CAD",
        locate: "en_CA",
        id: 8
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Thụy Sĩ",
        enName: "Switzerland",
        alpha2Code: "CH",
        alpha3Code: "CHE",
        viCurrencyName: "Franc Thụy Sĩ",
        iso4217code: "CHF",
        locate: "de_CH",
        id: 9
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Chile",
        enName: "Chile",
        alpha2Code: "CL",
        alpha3Code: "CHL",
        viCurrencyName: "Peso Chile",
        iso4217code: "CLP",
        locate: "es_CL",
        id: 10
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Trung Quốc",
        enName: "China",
        alpha2Code: "CN",
        alpha3Code: "CHN",
        viCurrencyName: "Nhân dân tệ",
        iso4217code: "CNY",
        locate: "zh_CN",
        id: 11
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Colombia",
        enName: "Colombia",
        alpha2Code: "CO",
        alpha3Code: "COL",
        viCurrencyName: "Peso Colombia",
        iso4217code: "COP",
        locate: "es_CO",
        id: 12
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Đức",
        enName: "Germany",
        alpha2Code: "DE",
        alpha3Code: "DEU",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "de_DE",
        id: 13
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Ecuador",
        enName: "Ecuador",
        alpha2Code: "EC",
        alpha3Code: "ECU",
        viCurrencyName: "Đô la Ecuador",
        iso4217code: "USD",
        locate: "es_EC",
        id: 14
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Tây Ban Nha",
        enName: "Spain",
        alpha2Code: "ES",
        alpha3Code: "ESP",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "es_ES",
        id: 15
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Pháp",
        enName: "France",
        alpha2Code: "FR",
        alpha3Code: "FRA",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "fr_FR",
        id: 16
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Anh",
        enName: "United Kingdom",
        alpha2Code: "GB",
        alpha3Code: "GBR",
        viCurrencyName: "Bảng Anh",
        iso4217code: "GBP",
        locate: "en_GB",
        id: 17
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Hy Lạp",
        enName: "Greece",
        alpha2Code: "GR",
        alpha3Code: "GRC",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "el_GR",
        id: 18
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Hồng Kông",
        enName: "Hong Kong",
        alpha2Code: "HK",
        alpha3Code: "HKG",
        viCurrencyName: "Đô la Hồng Kông",
        iso4217code: "HKD",
        locate: "zh_HK",
        id: 19
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Hungary",
        enName: "Hungary",
        alpha2Code: "HU",
        alpha3Code: "HUN",
        viCurrencyName: "Forint Hungary",
        iso4217code: "HUF",
        locate: "hu_HU",
        id: 20
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Indonesia",
        enName: "Indonesia",
        alpha2Code: "ID",
        alpha3Code: "IDN",
        viCurrencyName: "Rupiah Indonesia",
        iso4217code: "IDR",
        locate: "id_ID",
        id: 21
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Italy",
        enName: "Italy",
        alpha2Code: "IT",
        alpha3Code: "ITA",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "it_IT",
        id: 22
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Nhật Bản",
        enName: "Japan",
        alpha2Code: "JP",
        alpha3Code: "JPN",
        viCurrencyName: "Yên Nhật",
        iso4217code: "JPY",
        locate: "ja_JP",
        id: 23
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Campuchia (Cambodia)",
        enName: "Cambodia",
        alpha2Code: "KH",
        alpha3Code: "KHM",
        viCurrencyName: "Riel Campuchia",
        iso4217code: "KHR",
        locate: "km_KH",
        id: 24
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Hàn Quốc",
        enName: "South Korea",
        alpha2Code: "KR",
        alpha3Code: "KOR",
        viCurrencyName: "Won Hàn Quốc",
        iso4217code: "KRW",
        locate: "ko_KR",
        id: 25
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Lào",
        enName: "Laos",
        alpha2Code: "LA",
        alpha3Code: "LAO",
        viCurrencyName: "Kip Lào",
        iso4217code: "LAK",
        locate: "lo_LA",
        id: 26
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Mexico",
        enName: "Mexico",
        alpha2Code: "MX",
        alpha3Code: "MEX",
        viCurrencyName: "Peso Mexico",
        iso4217code: "MXN",
        locate: "es_MX",
        id: 27
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Myanmar (Burma)",
        enName: "Myanmar",
        alpha2Code: "MM",
        alpha3Code: "MMR",
        viCurrencyName: "Kyat Myanmar",
        iso4217code: "MMK",
        locate: "my_MM",
        id: 28
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Malaysia",
        enName: "Malaysia",
        alpha2Code: "MY",
        alpha3Code: "MYS",
        viCurrencyName: "Ringgit Malaysia",
        iso4217code: "MYR",
        locate: "ms_MY",
        id: 29
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Hà Lan",
        enName: "Netherlands",
        alpha2Code: "NL",
        alpha3Code: "NLD",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "nl_NL",
        id: 30
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "New Zealand",
        enName: "New Zealand",
        alpha2Code: "NZ",
        alpha3Code: "NZL",
        viCurrencyName: "Đô la New Zealand",
        iso4217code: "NZD",
        locate: "en_NZ",
        id: 31
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Peru",
        enName: "Peru",
        alpha2Code: "PE",
        alpha3Code: "PER",
        viCurrencyName: "Sol Peru",
        iso4217code: "PEN",
        locate: "es_PE",
        id: 32
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Philippines",
        enName: "Philippines",
        alpha2Code: "PH",
        alpha3Code: "PHL",
        viCurrencyName: "Peso Philippines",
        iso4217code: "PHP",
        locate: "en_PH",
        id: 33
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Ba Lan",
        enName: "Poland",
        alpha2Code: "PL",
        alpha3Code: "POL",
        viCurrencyName: "Zloty Ba Lan",
        iso4217code: "PLN",
        locate: "pl_PL",
        id: 34
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Hàn Quốc Bắc Triều Tiên",
        enName: "North Korea",
        alpha2Code: "KP",
        alpha3Code: "PRK",
        viCurrencyName: "Won Triều Tiên",
        iso4217code: "KPW",
        locate: "ko_KP",
        id: 35
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Bồ Đào Nha",
        enName: "Portugal",
        alpha2Code: "PT",
        alpha3Code: "PRT",
        viCurrencyName: "Euro",
        iso4217code: "EUR",
        locate: "pt_PT",
        id: 36
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Paraguay",
        enName: "Paraguay",
        alpha2Code: "PY",
        alpha3Code: "PRY",
        viCurrencyName: "Guarani Paraguay",
        iso4217code: "PYG",
        locate: "es_PY",
        id: 37
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Romania",
        enName: "Romania",
        alpha2Code: "RO",
        alpha3Code: "ROU",
        viCurrencyName: "Leu Romania",
        iso4217code: "RON",
        locate: "ro_RO",
        id: 38
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Singapore",
        enName: "Singapore",
        alpha2Code: "SG",
        alpha3Code: "SGP",
        viCurrencyName: "Đô la Singapore",
        iso4217code: "SGD",
        locate: "en_SG",
        id: 39
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Thụy Điển",
        enName: "Sweden",
        alpha2Code: "SE",
        alpha3Code: "SWE",
        viCurrencyName: "Krona Thụy Điển",
        iso4217code: "SEK",
        locate: "sv_SE",
        id: 40
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Thái Lan",
        enName: "Thailand",
        alpha2Code: "TH",
        alpha3Code: "THA",
        viCurrencyName: "Baht Thái",
        iso4217code: "THB",
        locate: "th_TH",
        id: 41
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Đài Loan",
        enName: "Taiwan",
        alpha2Code: "TW",
        alpha3Code: "TWN",
        viCurrencyName: "Đô la Đài Loan",
        iso4217code: "TWD",
        locate: "zh_TW",
        id: 42
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Uruguay",
        enName: "Uruguay",
        alpha2Code: "UY",
        alpha3Code: "URY",
        viCurrencyName: "Peso Uruguay",
        iso4217code: "UYU",
        locate: "es_UY",
        id: 43
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Hoa Kỳ",
        enName: "United States",
        alpha2Code: "US",
        alpha3Code: "USA",
        viCurrencyName: "Đô la Mỹ",
        iso4217code: "USD",
        locate: "en_US",
        id: 44
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Venezuela",
        enName: "Venezuela",
        alpha2Code: "VE",
        alpha3Code: "VEN",
        viCurrencyName: "Bolívar Venezuela",
        iso4217code: "VES",
        locate: "es_VE",
        id: 45
    },
    {
        isActive: 1,
        isDelete: 0,
        createdAt: new Date(),
        updatedAt: null,
        country: "Việt Nam",
        enName: "Vietnam",
        alpha2Code: "VN",
        alpha3Code: "VNM",
        viCurrencyName: "Đồng Việt Nam",
        iso4217code: "VND",
        locate: "vi_VN",
        id: 46
    }
]